export const APP_START_CLEAR_LOGIN = '[UserSessionAction] starting app temp solution clear previous login';
export const LOGIN_USER_ATTEMPT = '[UserSessionAction] attempt user-session log in';
export const LOGIN_USER_FAILURE = '[UserSessionAction] failed user-session log in';
export const LOGIN_USER_SUCCESS = '[UserSessionAction] successful user-session log in';
export const LOGOUT_USER_ATTEMPT = '[UserSessionAction] attempt user-session log out';
export const LOGOUT_USER_SUCCESS = '[UserSessionAction] success user-session log out';
export const LOGOUT_USER_FAILURE = '[UserSessionAction] failure user-session log out';
export const GET_SESSION_USER_ATTEMPT = '[UserSessionAction] get authorized user-session attempt';
export const GET_SESSION_USER_SUCCESS = '[UserSession] get authorized user-session success';